### ISSUE TITLE
Round line caps

### ISSUE THREAD

**Issue by bb-git** [andreipitis/ASPCircleChart#4]
The library looks great! Any chance to get some round line caps? I would like to achieve sth like in the image. 
Thanks
![08](https://cloud.githubusercontent.com/assets/7348507/19600544/d300a174-97a5-11e6-811b-647e2e5e9a83.png)

**Comment by andreipitis** [comment]
Hi, I'm glad you like it :).

I was thinking of implementing some kind of way to specify a custom shape for a slice, but I didn't have time to implement it yet, and it may take some time to develop.

In the meantime I think implementing an option to have round line caps sounds like a good idea.
I will push an update with the new feature in the following days, after I do some more testing to make sure everything works and looks alright.

**Comment by andreipitis** [comment]
I pushed the changes for this and included some bug fixes.
To get the result you are looking for use: 

``` swift
circleChart.itemSpacing = 0.0
circleChart.lineCapStyle = .round
circleChart.latestSliceOnTop = false
```

**Comment by bb-git** [comment]
Sounds great. I'm looking forward to hearing from you.

**Comment by andreipitis** [comment]
Hi @bb-git ,

The new feature is ready to use, please see my previous comment for a code sample.

**Comment by bb-git** [comment]
Awesome :). Thank you. I will try in the next days.
